[package]
name = "pitch-shifting"
version = "0.1.0"
edition = "2021"

[dependencies]
hound = "3.5.1"
num-traits = "0.2.19"
thiserror = "2.0.6"
rustfft = "6.2.0"
ndarray = "0.16.1"
num-complex = "0.4.6"
